### ISSUE TITLE
Attribute names always dasherized?

### ISSUE THREAD

**Issue by xbill82** [SeyZ/jsonapi-serializer#10]
Hi,
I have noticed that attribute names written in camelCase (such as `nbItems`) are dasherized (like `nb-items`). It sounds nice, but wouldn't it be even nicer to give the choice through a flag (like `dasherize`, which could be `true` by default)?

**Comment by SeyZ** [comment]
Yes, I agree with the concept @xbill82.

I suggest to have an option which is a function that maps the attribute instead of having options like `dasherize: true` or `camelCase:true` or even `underscore: true`.

Something like:

`keyForAttribute: function (attribute) { return camelCase(attribute); }`

Thoughts?

**Comment by xbill82** [comment]
Yeah, sounds fair!
So, this way the `attributes` field would become an `object` instead of an `array`? I say this because of the `key: function` structure you suggest...

**Comment by xbill82** [comment]
And, also, there could be a couple of `dasherize(attr)`, `camelCase(attr)` and `underscore(attr)` functions provided by the main `JsonApiSerializer` class, e.g.

    new JsonApiSerializer('users', dataSet, {
        apiEndpoint: 'http://localhost:3000/api',
        attributes: {'firstName': function(attr){ return JsonApiSerializer.camelCase(attr)} },
      }

**Comment by SeyZ** [comment]
@xbill82 The master branch has been updated to have this new feature. Example:

```
var inflection = require('inflection');

new JsonApiSerializer('users', dataSet, {
    apiEndpoint: 'http://localhost:3000/api',
    attributes: ['firstName', 'lastName'],
    keyForAttribute: function (attribute) {
      return inflection.camelCase(attribute);
    }
  }
```

Thoughts? Does it fix your problem?

**Comment by xbill82** [comment]
Sounds terrific. :+1: 
Just one thing: are you sure the name `keyForAttribute` would be easy to understand? I think we're dealing with attribute key transform, so I'd suggest something like `transformAttributeKeys` or something similar.
Would be happy to read your thoughts about it.

**Comment by SeyZ** [comment]
No, I'm not sure :) Ember.js uses this name to do the same thing:
http://emberjs.com/api/data/classes/DS.JSONSerializer.html#method_keyForAttribute

**Comment by xbill82** [comment]
Good point! Ember is a great source of inspiration for conventions and habits! Great job!

**Comment by SeyZ** [comment]
Thanks @xbill82 !
