### ISSUE TITLE
Deserializing id back to _id

### ISSUE THREAD

**Issue by prashaantt** [SeyZ/jsonapi-serializer#100]
The serializer has the option to specify an alternate field as the id for a resource. This comes in handy when working with databases (notably MongoDB):

``` js
new Serializer("users", { id: "_id" }).serialize(users);
```

I wonder why the same facility isn't available for deserialization so that after transport, the id can be properly mapped back to the appropriate field in the model:

``` js
new Deserializer({ id: "_id" }).deserialize(users);
```

**Comment by jcw-** [comment]
Yes! Just ran into exactly the same thing. Next I tried using a function for keyForAttribute in order to manually do the substitution, but unfortunately id is never send through that method.

**Comment by prashaantt** [comment]
@jcw- FWIW, I worked around this by manually assigning the _id field to a new id attribute after deserialization, something like:

```js
user.id = user._id;
delete user._id;
```

This is trivial to do, but it should ideally be built-in.

**Comment by bschnelle** [comment]
Here's another option that may be of interest to you.  https://github.com/kutlerskaggs/json-api-ify

**Comment by SeyZ** [comment]
I've added the support of the id option ;-) FYI, here's the test:

```
  describe('id', function () {
    it('should override the id field', function (done) {
      var dataSet = {
        data: [{
          type: 'users',
          id: '54735750e16638ba1eee59cb',
          attributes: { 'first-name': 'Sandro', 'last-name': 'Munda' }
        }, {
          type: 'users',
          id: '5490143e69e49d0c8f9fc6bc',
          attributes: { 'first-name': 'Lawrence', 'last-name': 'Bennett' }
        }]
      };

      new JSONAPIDeserializer({
        id: '_id'
      }).deserialize(dataSet, function (err, json) {
        expect(json[0]).to.not.have.keys('id');
        expect(json[1]).to.not.have.keys('id');
        expect(json[0]._id).equal('54735750e16638ba1eee59cb');
        expect(json[1]._id).equal('5490143e69e49d0c8f9fc6bc');
        done(null, json);
      });

    });
  });
```

**Comment by dhautotlf** [comment]
Nice! 😄 
@SeyZ any ETA for the next release ?
