### ISSUE TITLE
additional collaborators?

### ISSUE THREAD

**Issue by jamesdixon** [SeyZ/jsonapi-serializer#105]
Hi,

I was curious if you'd be willing to open the project up to additional collaborators? I know maintaining an open-source project is a lot of time and given that we're all busy, it might be great for you to have an extra hand in maintaining a very core, project. 

We're using this serializer extensively in our project and we'd love to continue to contribute.

Thanks again for all your hard work!

Cheers,
James

**Comment by SeyZ** [comment]
You're right, I've sent you an invite :) Sorry for the delay !

**Comment by jamesdixon** [comment]
@SeyZ no worries at all! Thanks for the invite!
