### ISSUE TITLE
Add option to prevent null values in dataset

### ISSUE THREAD

**Issue by jcao02** [SeyZ/jsonapi-serializer#106]
You just added automatic null value in missing attributes in the data set in this commit 97cbfed67abc8d54dc9958fc779dfb667f2ac563. However, I believe this behavior should not be automatic specially in a `PATCH` were `null` will replace the previous value of a top level attribute and deletes a relationship. What do you think of adding an option `ignoreMissingAttribute` to the relationship object which if true, it won't set the relationship to null, or perhaps go back to the original behavior explicitly setting an attribute `null` if you want it to be serialized as `null`

**Comment by jcao02** [comment]
Ï realized you added this behavior so `ignoreRelationshipData` could work as you expected. Perhaps a better solution is to set null the attribute if the option present on it:
``` 
if (!(splittedAttributes[0] in record) && opts[attribute] && opts[attribute].ignoreRelationshipData) {
    record[splittedAttributes[0]] = null;
}
```

**Comment by SeyZ** [comment]
Hey @jcao02 thank you for the report and the fix! I think it's not a good idea to use the same `ignoreRelationshipData` ignore. I prefer `ignoreMissingAttribute` option :)
