### ISSUE TITLE
Using `type` as an attribute within a model

### ISSUE THREAD

**Issue by dangreenisrael** [SeyZ/jsonapi-serializer#108]
Hi Sandro,

First of all, thank you so much for making this awesome serializer.  It has been a huge life saver and it performs very well.

However, we do have one issue that is making including records problematic. In many of our models we use `type` as an arbitrary value to describe the record.  This has become a problem for two reasons.

1 - If the value of `type` is `null` we get the following error:
```
TypeError: Cannot read property 'type' of null
    at OUR_APP_DIRECTORY/node_modules/jsonapi-serializer/lib/serializer-utils.js:185:29
    at Array.forEach (native)
```

2 - If the value is not `null`, the attribute (`type`) is stripped out of the attributes for the record. 

We are able to override the actual `type` for the record but we still lose the attribute.

Here is an example of `type` `colour`

```javascript
[
  {
    id: 1,
    type: "red"
    shade: "dark"
  },
  {
    id: 2
    type: "blue"
    shade: "light"
  }
]
```
We manually set `type` to `colour` using `typeForAttribute` but we lose the property `type`

Output:

```javascript
[
  id: 1,
  type: "colour"
  {
    shade: "dark"
  },
  id: 2,
  type: "colour"
  {
    shade: "light"
  }
]
```

Expected:

```javascript
[
  id: 1,
  type: "colour"
  {
    type: "red",
    shade: "dark"
  },
  id: 2,
  type: "colour"
  {
    type: "blue",
    shade: "light"
  }
]
```

Would it be possible ignore the `type` attribute when using `typeForAttribute` or to add a flag to ignore it outright?

**Comment by jamesdixon** [comment]
@dangreenisrael I don't see an issue with ensuring that `type` is ignored when it's part of the attributes. Is this something you'd be willing to submit a PR for?

**Comment by dangreenisrael** [comment]
Awesome, thanks @jamesdixon

**Comment by dangreenisrael** [comment]
After further review, it turns out that the issue was caused by a quirk in my code. I'm going to close the issue.

Thanks for your time and the awesome repo.
