### ISSUE TITLE
Handling mixed type collections

### ISSUE THREAD

**Issue by antondomratchev** [SeyZ/jsonapi-serializer#109]
@SeyZ I currently working on handling mixed type collections which requires some way of identifying the type of the object in the collection in order to be handled properly. 

I am exploring the idea of extending the options for deserializer to toggle passing the type along with the attributes list (similarly to how you pass the id). My implementation will have a side effect of overwriting a key of `'type'` if present in the attributes  object which may break intended behavior.

I was wondering if you had any thoughts of identifying the different types of objects in a mixed collection?

https://github.com/GrokInteractive/jsonapi-serializer/commit/8e55a2a7d995693f2f5a4fd66211acac5bbc6611

**Comment by SeyZ** [comment]
Hey @antondomratchev sorry for delay. I'm not sure to understand the use case you described. Is it something people generally want or do you think it's very specific to your usage?

**Comment by antondomratchev** [comment]
@SeyZ, This was solving a specific problem that I had, I am not sure if this would solve the problem for anyone else.

To describe my problem a little better, I was working on deserializing data array with mixed types returned by search endpoint and I wanted to retain the `type` attribute to handle the data appropriately in my app. In my case, my data array contained users, videos, hashtags, locations etc.
here is an example mixed type collection I was working with:
```json
{ 'data': [
 { 'id': '1', 'type': 'user'},
 { 'id': '2', 'type': 'video'},
 { 'id': '12', 'type': 'location'},
 { 'id': '121', 'type': 'hashtag'},
]
}, 'included': { //Above listed objects included here }
```

I think anyone using your awesome deserializer package would benefit from this functionality when working with mixed type collections. Since this behavior is configurable ( I can update the Docs) via the options object its turned off by default and will not break existing implementations. It's entirely up to you if you would like to bring this functionality into your package. We are currently using the fork branch in our production code.

**Comment by SeyZ** [comment]
Thank you for the clarification @antondomratchev ! I'm just wondering if it's JSONAPI compliant to have "mixed types" in 1 document like your example? If so, I think we can merge this on master :)

**Comment by antondomratchev** [comment]
Here is what I found on the subject.
http://discuss.jsonapi.org/t/how-to-implement-a-search-api/35/3

**Comment by SeyZ** [comment]
Sounds good @antondomratchev thank you! It's now merged 👍
