### ISSUE TITLE
valueForAttribute

### ISSUE THREAD

**Issue by amk221** [SeyZ/jsonapi-serializer#110]
Suggestion for this function when deserializing. It would be useful to coerce attributes back to an appropriate value

```javascript
return new JSONAPIDeserializer({
  valueForAttribute(key, attribute) {
    if (key === 'size') {
      let size = parseFloat(attribute);
      return isNaN(size) ? null : size;
    } else {
      return attribute;
    }
  },

  valueForRelationship(key, relationship) {

  }
}).deserialize(dataSet);
```

**Comment by antondomratchev** [comment]
@amk221 I am not seeing how this would be the job of the deserializer. You can simply map over the returned collection to transform the data to the desired state.

**Comment by amk221** [comment]
ok!

**Comment by amk221** [comment]
I think I was confused at the time, would Transforms be enough?
