### ISSUE TITLE
How to add `relationshipLinks` if data not exist

### ISSUE THREAD

**Issue by zion03** [SeyZ/jsonapi-serializer#115]
How I can add relation as link always? 
I want to add `lessons` relation as link, but it's works only if I `include` Lessons property to object which will serialized.
Example:

```
module.exports = {
  attributes: ['name', 'Lessons'],
  Lessons: {
    ignoreRelationshipData: true,
    included: false,
    relationshipLinks: {
      related: 'lessons'
    }
  }
};
```

**Comment by SeyZ** [comment]
Hey @zion03 You can use the option `nullIfmissing: true` :)
Reopen this issue if you still have a problem, thanks!
