### ISSUE TITLE
NullIfMissing use undefined instead of null

### ISSUE THREAD

**Issue by thomasthiebaud** [SeyZ/jsonapi-serializer#118]
If set the key `NullIfMissing` to `true`, but instead of having `null`, I have `undefined`

I get

    "attributes": {
      "name": "Gandalf"
      "preprocessing": [undefined]
    }

instead of 

    "attributes": {
      "name": "Gandalf"
      "preprocessing": [null]
    }

I checked the test [here](https://github.com/SeyZ/jsonapi-serializer/blob/master/test/serializer.js#L1806). Instead of 

    expect(json.data[0].relationships.address.data).to.be.empty;

was it not supposed to be 

    expect(json.data[0].relationships.address.data).to.be.null;

**Comment by SeyZ** [comment]
Thanks @thomasthiebaud ! It's now fixed 👍
