### ISSUE TITLE
Does not properly serialize data in nested Mongoose documents

### ISSUE THREAD

**Issue by espenhogbakk** [SeyZ/jsonapi-serializer#119]
I had a problem with my nested documents not serializing correctly, I had a look in your [tests](https://github.com/SeyZ/jsonapi-serializer/blob/master/test/serializer.js#L544) and I see that it should work.

I found out that the problem was that I was passing in a Mongoose model document, not an ordinary object. As soon as I did "model.toObject()", it worked perfectly. The serializer did output the data, but it did not dash-case it correctly etc.

**Comment by awochna** [comment]
Hi @espenhogbakk!

Can you give us an example of what you are serializing, the options you're using, and the output you got when you serialized it? Also tell us what you expected the output to look like.

That'll go a long way to helping us help you. :smile:

**Comment by SeyZ** [comment]
Hey @espenhogbakk - please, reopen this issue if you have more information about the improvements you want. I think passing a real JSON is always better (using `.lean()` in mongoose or using `.toObject()` like you said)
