### ISSUE TITLE
Can't select object properties to serialize

### ISSUE THREAD

**Issue by mcalthrop** [SeyZ/jsonapi-serializer#120]
I have data in my Mongo DB that looks like this:

``` js
[
  {
    role: 'admin',
    local: {
      password: '___password_hash___',
      email: 'admin@example.com'
    }
  },
  {
    role: 'standard',
    local: {
      password: '___password_hash___',
      email: 'standard@example.com'
    }
  }
]
```

I want to write a serializer that excludes the `password` property (for obvious reasons), so that each `user` object would look like this:

``` js
{
  role: 'admin',
  local: {
    email: 'admin@example.com'
  }
}
```

I've tried this as a serializer:

``` js
const JSONAPISerializer = require('jsonapi-serializer').Serializer;

module.exports = new JSONAPISerializer('user', {
  attributes: ['role', 'local'],
  local: {
    attributes: ['email']
  },
  pluralizeType: false,
  keyForAttribute: 'camelCase'
});
```

My understanding is that the `attributes: ['email']` line specifies the list of attributes in the `local` object that should be returned – and that no other attributes will be returned.

However, even using that serializer, I still get this returned:

``` json
{
  "data": [
    {
      "type": "user",
      "id": "587e6c7a62af4891d801b0c8",
      "attributes": {
        "role": "admin",
        "local": {
          "email": "admin@example.com",
          "password": "___password_hash___"
        }
      }
    },
    {
      ...
    }
]
```

Help! What should I be doing? I must be missing something small.

**Comment by SeyZ** [comment]
Hey @mcalthrop I think it's because you pass a MongoDB object to the serializer instead of just a "plain JSON". Can you try to pass your object after `toJSON()` called?

**Comment by mcalthrop** [comment]
Thanks for the quick reply @SeyZ :-)

I've tried calling `.toJSON()` on the result from Mongoose, but the method does not exist.

For a bit of context, here's the code around the call to the serializer:

``` js
const UserModel = require('../models/user.model');
const UserSerializer = require('../serializers/user.serializer');

function usersIndex(req, res) {
  UserModel.find((err, users) => {
    // error check removed for brevity
    console.log(users);
    return res.status(200).send(UserSerializer.serialize(users));
  });
}
```

And the output of that `console.log()` looks like this:

```
[ { _id: 587e6c7a62af4891d801b0c8,
    role: 'admin',
    __v: 0,
    local:
     { password: '___password_hash___',
       email: 'admin22@example.com' } },
...
]
```

What do you suggest as my next step?

**Comment by mcalthrop** [comment]
btw, my Mongoose model looks like this:

``` js
const mongoose = require('mongoose');
const bcrypt = require('bcrypt-nodejs');
const validRoles = ['admin', 'standard'];

const userSchema = mongoose.Schema({
  role: { type: String, required: true, enum: validRoles },
  local: {
    email: { type: String, unique: true, required: true },
    password: { type: String, required: true }
  }
});

userSchema.methods.generateHash = function(password) {
  return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
};

userSchema.methods.validPassword = function(password) {
  return bcrypt.compareSync(password, this.local.password);
};

userSchema.statics.validRoles = () => validRoles;

userSchema.statics.isRoleValid = (roleToCheck) => validRoles.includes(roleToCheck);

userSchema.set('toJSON', {
  versionKey: false,
  transform: (doc, json) => {
    delete json.local.password;

    return json;
  }
});

module.exports = mongoose.model('User', userSchema);
```

**Comment by mcalthrop** [comment]
Hi @SeyZ 

I've tried manually removing the extra fields inserted by Mongo for each document (`_id` and `__v`), but I'm still having the same issues.

Do you have any more suggestions?

This is a blocker for me at the moment.

many thanks

Matt

**Comment by mcalthrop** [comment]
Found the issue.

Turns out I had to call `toJSON()` on each individual item in the array (previously I had been calling it on the whole array) :

``` js
  UserModel.find((err, users) => {
    const usersToJSON = users.map((user) => user.toJSON()); // <--- this
    const serializedUsers = UserSerializer.serialize(usersToJSON);
    return res.status(200).send(serializedUsers);
  });
```

One other thing I had to do was to explicitly add the field `_id` in the serializer:

``` js
const UserSerializer = new JSONAPISerializer('user', {
  attributes: ['role', 'local'],
  id: '_id', // <--- this
  local: {
    attributes: ['email']
  },
  pluralizeType: false,
  keyForAttribute: 'camelCase'
});
```

For some reason it was not automatically extracted.

**Comment by SeyZ** [comment]
@mcalthrop you can also use `lean()` function in Mongoose to have directly plain JSON instead of Mongoose documents ;)

**Comment by mcalthrop** [comment]
@SeyZ: ah, thanks for that... it's simplified my code. Cheers!
