### ISSUE TITLE
Cleaning up dependencies to help with bundle size

### ISSUE THREAD

**Issue by hartzis** [SeyZ/jsonapi-serializer#123]
sandro,

Thanks for all the awesome work with this package. After looking at a lot of other JSON api serialize/deserialize libraries this is one of the best for sure.

We're looking into using this on the front end to help with handling JSON api's and are curious about cleaning up some of the deps to create a smaller bundle size via webpack. Let me know your thoughts on this please.

"easy" deps to clean up for smaller size:
- [x] (pr #125) use `var isObject = require('lodash/isObject')` instead of `var _ = require('lodash')`
  - jdalton taks about this approach [here](https://github.com/postaljs/postal.js/issues/91#issuecomment-73159144)
- [x] (pr #124) remove `bluebird` as a dependency, just use native `Promise`, also noted in [issue 62](https://github.com/SeyZ/jsonapi-serializer/issues/62#issuecomment-195285032)
  * This would probably require a major release as Node v0.10 doesn't have `Promise` support and is [still has a 30% share in production](https://semaphoreci.com/blog/2016/10/12/nodejs-versions-used-in-commercial-projects-2016-edition.html)

"harder" deps to clean up:
- [ ] remove `inflected` dependency for `keyForAttribute` and instead default to `(k) => k` ?
- [ ] remove `inflected` dependency for `pluralizeType` and instead default to `(k) => k + 's'`?
- Users could require `inflected` themselves and put `Inflector.dasherize` for `keyForAttribute` and `Inflector.pluralize` for `pluralizeType`

Going to make a PRs for the `bluebird` and `lodash` cleans up.

Thanks again and cheers!
-Brian Emil

**Comment by hartzis** [comment]
As a side note, noticed that the `browserify` folder and contained js hasn't been updated consistently with releases. Possibly cleanup/remove the browserify folder and related build all together?

I feel solving the above listed dependency issues could help unify the package for both node and web.

**Comment by jamesdixon** [comment]
@hartzis when Node first introduced native promise support, I recall the performance just wasn't up to par with Bluebird. Do you know if this is still the case?

**Comment by hartzis** [comment]
@jamesdixon you're definitely correct, [bluebird performance](http://bluebirdjs.com/docs/benchmarks.html).

Though I don't think just because it has better performance than native Promises is a reason to require bluebird as a dependency.

However someone who is concerned about performance can 'globally polyfill' `Promise` via `global.Promise = require('bluebird')` and on the web side via `window.Promise`.

To that effect, removing `bluebird` as a required dependency helps reduce the overall bundle size for both node and web. As a point of reference, `bluebird` gzipped/minified is [17kb](http://bluebirdjs.com/docs/install.html)

**Comment by jamesdixon** [comment]
@hartzis not saying it's a reason to NOT remove Bluebird, but it's certainly an important point and something to note in the documentation (regarding the polyfill) when making this change. Otherwise, I'm all for it :)

**Comment by hartzis** [comment]
@jamesdixon definitely a good point about documenting the change and the polyfill option. I can update the PR, #124, to include details on the change.

**Comment by SeyZ** [comment]
Merged guys! thank you so much @hartzis

**Comment by hartzis** [comment]
@SeyZ you rock! closing and moving the other stuff to a new issue to discuss.
