### ISSUE TITLE
Serializing documents with only relationships (no attributes).

### ISSUE THREAD

**Issue by jprdupont** [SeyZ/jsonapi-serializer#126]
Resource documents without attributes (e.g. only relationships) aren't added to the top-level `includes` array. Was that by design?

https://github.com/SeyZ/jsonapi-serializer/blame/master/lib/serializer-utils.js lines 190 and 191 - should this read:

if ((includedAttrs.length **|| relationships.length**) && (_.isUndefined(opts.included) || opts.included))

**Comment by psheraton** [comment]
Ran into this same problem today. Relationship only resources seem like they should be supported or if not, there should be some indication of an issue.
