### ISSUE TITLE
Handling `null` values as a 404 error

### ISSUE THREAD

**Issue by sarus** [SeyZ/jsonapi-serializer#13]
Hello,

I wanted to get your thoughts on having the jsonapi-serializer library handle `404` resource not found errors for you.  I know the error object specified by the JSON API is pretty open ended so it might not make sense to try and include it in this library.

I'm imagining something where if you pass `null` as the value to the JSONAPISerializer constructor it would return back a properly formatted JSON API 404 error

``` json
{
        "errors": [{
            "status": "404",
            "code": "Not Found",
            "title": "'User Not Found",
            "detail": "The resource 'user' could not be found",
            "source":{
                "pointer": "/data"
            }
        }]
}
```

This is of course fairly easy to handle directly outside of JSONAPISerializer but it might be nice to provide the basic error handling for when a resource doesn't exist.  The other `404` like condition is when a relationship doesn't exist for a resource that already exists.  In this case you have to return an empty array for the data versus a `404` so there needs to be a way to differentiate these two cases.

Other types of errors such as Bad Request would probably have to be handled outside of this library.  

JSON API Documenation related to this:
http://jsonapi.org/format/#fetching-resources-responses-200
http://jsonapi.org/format/#fetching-resources-responses-404
http://jsonapi.org/format/#errors

**Comment by sarus** [comment]
Just to provide some more details here is how I am currently handling it.  

```javascript
UserSerializer.prototype.serialize = function(users){
    var self = this;

    if(!users){
        return new RSVP.Promise(function(resolve, reject){
            var error = self.jsonApiError.serialize({
                status: "404",
                summary: errors.USER_NOT_FOUND,
                detail: "The user was not found"
            });
            reject(error);
        });
    }

    return new JSONAPISerializer('users', users, {
        topLevelLinks: {self: self._getLinksUrl('users')},
        dataLinks: {
            self: function(user){
                return self._getLinksUrl('users/' + user.id);
            }
        },
        attributes: ['username', 'email', 'full_name', 'is_admin', 'enabled', 'last_login']
    })
};
```
`jsonApiError` is a utility class that helps to create a JSON API compliant JSON error object.

Then code using the serializer does something like this.  

```javascript
            self.userSerializer.serialize(result.rows[0]).then(function(users){
                cb(null, users);
            }, function(err){
                //404 error
                cb(err);
            }).finally(function(){
                done();
            });
```

`result` is the result returned from the node `pg` postgres module.  If there are no results then result.rows[0] is undefined.  In the case of a resource collection `result.rows` is just an empty array and you get the proper JSON API response for an empty collection.

**Comment by SeyZ** [comment]
Error handling is not available ;)
