### ISSUE TITLE
Make sure links are always there

### ISSUE THREAD

**Issue by karellm** [SeyZ/jsonapi-serializer#134]
Hi,

I use this package with sequelize. I'm a little confused at how I can make sure `links` are always included. For instance a `school` has `students`, I might want to return the school without including the `students` (I don't want to include them in the sequelize query, nor the returned payload). That said I want to show the links to get the students.

Any idea how I can make that happen? Thanks!

```
{
  attributes: [
    'name',
    'students'
  ],
  students: {
    include: false,
    ref: 'id',
    ignoreRelationshipData: true,
    relationshipLinks: {
      related: (school) => `/schools/${school.id}/students`
    }
  }
}
```

The above serializer will not return the `relationships` object unless I query the school like so:

```js
School.findOne({
  where: { id: 1 },
  include: [ { model: Student, as: 'students' } ],
})
```

**Comment by karellm** [comment]
@SeyZ Sorry to be pushy (I know it's barely been a day since I posted) but this is blocking us in a project we are working on and we are short on time. I would greatly appreciate if you had couple minutes to help. Thanks :)

**Comment by SeyZ** [comment]
Hey @karellm 

You can use the option:
`nullIfMissing` (Set the attribute to null if missing from your data input. Default: false.)

```
{
  attributes: [
    'name',
    'students'
  ],
  students: {
    include: false,
    ref: 'id',
    ignoreRelationshipData: true,
    nullIfMissing: true // Include the students relationships even if you didn't make the JOIN in your sequelize request
    relationshipLinks: {
      related: (school) => `/schools/${school.id}/students`
    }
  }
}
```
With this option, you don't have to include your "students" in your Sequelize query :) Please, reopen this issue if you still have a problem.

Thanks!

**Comment by karellm** [comment]
@SeyZ Thanks for getting back to me. I did try that and it didn't work. 

We faced so many issues with `jsonapi-serializer` that we are currently switching to `json-api-serializer`. I saw you posted there to ask @danivek to join forces but if I can make a suggestion, I would recommend the other way around.

Here is my experience so far:

- `jsonapi-serializer` mad us go crazy couple times and overall felt like it was behaving quite inconsistently. Deep nesting sometimes didn't work. Same for `nullIfMissing`. I wish I could provide you failing test cases but I don't really have the bandwidth right now.
- `jsonapi-serializer` test suite is extremely hard to read and sometimes feels like it is not testing what it should be testing. I think you could either use better tests or better documentation.
- `json-api-serializer`'s api is extremely simple and clean. More importantly, it behaves like expected, I haven't had an issue so far (I have played only a day with it so we'll see here). 
- Deserializing relationships shouldn't be a thing (I know you have a card for this)
- Registering serializers make their use a breeze. I really dig that feature.

I really don't mean to diminish the work you're doing here. I just thought I would share my personal experience. Thanks for making this OS, I know what it takes to maintain such projects!

**Comment by SeyZ** [comment]
Hey @karellm thank you very much for the feedback ! I would love to have a test case to reproduce your issue because I don't get it. No worries for json-api-serializer, if you solve all your issues with it it's very very cool :) We're not in a competition, it's OSS world 👍
