### ISSUE TITLE
Compound Document Included Resource Self Links Incorrect?

### ISSUE THREAD

**Issue by IanVS** [SeyZ/jsonapi-serializer#14]
I'm still trying to learn json-api, but the example in the README does not seem to correspond to the spec at:  http://jsonapi.org/format/#document-compound-documents

The issue is the `self` links in the included resources.  The readme shows these as links to a relationship:

```
"included": [{
  .
  .
  .
  "links": {
    self: 'http://example.com/relationships/author',
    related: 'http://example.com/books/1/author'
  }
}
```

whereas the spec gives a link to the resource itself:

```
"included": [{
  .
  .
  .
  "links": {
    "self": "http://example.com/people/9"
  }
}
```

Is this an error in the README or am I misunderstanding?

**Comment by SeyZ** [comment]
Yes but, do you think json-api enforce the links format? In the `jsonapi-serializer` library, you're free to use the value you want.

**Comment by IanVS** [comment]
Sure, this clearly isn't a problem in the serializer, I was just more concerned about the README being incorrect or confusing for new users like me.

**Comment by SeyZ** [comment]
@IanVS I understand your request. Could you modify the README through a pull request? If you have no time, I can handle this :+1: 

What do you prefer?
