### ISSUE TITLE
AngularJS integration

### ISSUE THREAD

**Issue by kuiperr005** [SeyZ/jsonapi-serializer#150]
Hi here, great library! Any idea how to load this module into an existing AngularJS application? I've tried to add 'jsonapi-serializer' to my list of dependencies, but it keeps saying 'Module undefined'.

**Comment by mansona** [comment]
Hey @kuiperr005 the answer to this really depends on how you are building you Angular application, and how you are adding it as a dependency. Are you trying to include it via npm?

**Comment by kuiperr005** [comment]
Yes I am, I'm now using [this fork](https://github.com/mohuk/ts-jsonapi) and that's working fine

**Comment by mansona** [comment]
Great 🎉  glad it's working for you @kuiperr005 

If you don't have anything else you need help with could you close the issue 👍
