### ISSUE TITLE
Using jsonapi-serializer in the browser

### ISSUE THREAD

**Issue by sarus** [SeyZ/jsonapi-serializer#16]
Has anyone tried using this in the browser?  I'm curious if it can be combined with ember-cli-mirage to mock server endpoints for ember testing.

Would be super useful to be able to use it in that capacity.  I'm going to play around with it a bit to see if I can get this working but wanted to check and see if this is already a use case for anyone.

Thanks!

**Comment by SeyZ** [comment]
Indeed, it would be awesome to have jsonapi-serializer working on the browser and to combine it (for example) with ember-cli-mirage.

Awesome idea! Thanks!

**Comment by SeyZ** [comment]
Hey @sarus 

I tested the lib in the browser thanks to `browserify`. It seems to work well.
Can you confirm me?

Thanks!

**Comment by SeyZ** [comment]
@sarus Feel free to comment and reopen this issue if you can't use this library in the browser. Normally, it's fixed and works well :+1:
