### ISSUE TITLE
push new version to npm, or create new tag

### ISSUE THREAD

**Issue by kernel-io** [SeyZ/jsonapi-serializer#161]
Certain patches aren't live on the 3.5.5 version, released 4 months ago, namely this patch that was merged 3 months ago.

https://github.com/SeyZ/jsonapi-serializer/commit/85d90689bcf34607d0734dc910d5598caca79b54

**Comment by SeyZ** [comment]
Hey @kernel-io thanks for the issue - just released the `3.5.6` version on NPM ;)
