### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by mansona** [SeyZ/jsonapi-serializer#164]
Howdy 👋 Happy 2018 and I hope everything is well with you 🎉 

I just wanted to open this issue because I want to help you with this project, I understand work and life can get busy so please don't read any of this in a negative way 😄 Over the past year I have been building more and more that depends on this package and I want to give back in whatever way I can. 

Let me know if you would like to have a call at some time to discuss 👍

**Comment by SeyZ** [comment]
hey @mansona - thank you for the kind words and happy 2018 too :-)

I'm very happy to see this package is useful on your projects. you can contact me here to schedule a call :-) sandro@munda.me

Thanks!
