### ISSUE TITLE
Why promises?

### ISSUE THREAD

**Issue by AaronSikes** [SeyZ/jsonapi-serializer#17]
It looks like this library is performing only synchronous operations. It could just `return payload`, but instead it does:
```
return new P(function (resolve) {
  resolve(payload);
});
```
Why introduce the asynchronicity?

**Comment by SeyZ** [comment]
Totally right. I think we need to remove the promise stuff.

**Comment by IanVS** [comment]
Will you also be updating the README and bumping the major version?

**Comment by SeyZ** [comment]
Yes @IanVS I will do that as soon as possible. Thanks

**Comment by IanVS** [comment]
Awesome.  I'm using this project to enable jsonapi responses from sails.js.  So far, so good!  Thanks for the hard work!

**Comment by SeyZ** [comment]
Thanks and done @IanVS 

I wrote this wiki entry: https://github.com/SeyZ/jsonapi-serializer/wiki/Migrate-from-1.x-to-2.x

**Comment by IanVS** [comment]
Thanks, will you be publishing to npm as well?  I'm getting:

```
npm ERR! notarget No compatible version found: jsonapi-serializer@'>=2.0.0-beta.1 <3.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3","1.0.1","1.0.2","1.0.3","1.0.4"]
```

**Comment by rohanthacker** [comment]
Has this changed the syntax used? I'm unable to get any output using the serializer

**Comment by SeyZ** [comment]
@rohanthacker My bad. I forgot to update the README. I'm doing it right now.

**Comment by rohanthacker** [comment]
@SeyZ  No issues. Looking forward to it. Will update the express example if you need some help.

**Comment by SeyZ** [comment]
Thanks @rohanthacker I just updated too ;)

**Comment by rohanthacker** [comment]
@SeyZ  Looks Good. Thank you for the quick action .

**Comment by SeyZ** [comment]
:+1:
