### ISSUE TITLE
How can I build deep relationships with my serializer

### ISSUE THREAD

**Issue by zubeirtech** [SeyZ/jsonapi-serializer#214]
Here is what I am trying to do:

```javascript

return new JSONAPISerializer('post', {
      id: 'fe_id',
      attributes: ['channel_id', 'title', 'description', 'thumbnail_url', 'video_url', 'views', 'createdAt', 'channel', 'upvotes', 'comments'],
      channel: {
        ref: 'id',
        attributes: ['channelname', 'firstname', 'lastname', 'biography', 'image_url']
      },
      upvotes: {
        ref: 'id', 
        attributes: ['post_id', 'channel_id']
      },
      comments: {
        ref: 'id',
        attributes: ['post_id', 'channel_id', 'comment', 'channel'],
        channel: {
          ref: 'id',
          attributes: ['channelname', 'firstname', 'lastname', 'biography', 'image_url']
        }
      }
    }).serialize(data);

```

So basically putting a relationship within a relationship. It does not work, the response does not contain the data. What can I do, and is it possible ?

**Comment by TMiguelT** [comment]
I believe it should be possible. Check out the test for it here: https://github.com/SeyZ/jsonapi-serializer/blob/65e483a6d7ffda3fff869c2c3aa9553d096f56e6/test/serializer.js#L880-L932.

I can't see anything you're doing wrong in your code though, perhaps post the data you're trying to serialize as well?
