### ISSUE TITLE
Usage with Sequelize

### ISSUE THREAD

**Issue by rohanthacker** [SeyZ/jsonapi-serializer#23]
Trying to use this serializer with the ORM Sequelize. Is this possible? 
As of now I am receiving a the JSON API formatted json but with empty attributes.

routes/employee.js 
```javascript
router.get('/', function (req, res) {
  models.Employee.findAll().then(function(employees) {
    var json = new EmployeeSerializer(employees).serialize();
    res.send(employees);
      });
    });
```

serializers/employee.js
```javascript
function EmployeeSerializer(employee) {

  this.serialize = function () {
    return new JSONAPISerializer('employees', employee, {
      topLevelLinks: { self: 'http://localhost:3000/employees' },
      dataLinks: {
        self: function (employee) {
          return 'http://localhost:3000/employees/' + employee.id
        }
 },
      attributes: ['firstName', 'lastName'],
    });
  };
}

module.exports = EmployeeSerializer;
```

But the output to the above is 

```json
{
  "links": {
    "self": "http://localhost:3000/employees"
  },
  "data": [
    {
      "type": "employees",
      "id": "1",
      "attributes": {},
      "links": {
        "self": "http://localhost:3000/employees/1"
      }
    }
  ]
}

```

Any idea as to why this happens? Have I made an error?

**Comment by SeyZ** [comment]
I use Sequelize often too. I think you just forgot to use `toJSON()` before passing the payload to the `JSONAPISerializer`:

``` javascript
models.Employee.findAll().then(function(employees) {
    var json = new EmployeeSerializer(employees.toJSON()).serialize();
    res.send(employees);
  });
});
```

**Comment by rohanthacker** [comment]
Yup, this seems to be the issue. The data is nested in the Sequelize object.

**Comment by SeyZ** [comment]
:+1:

**Comment by rohanthacker** [comment]
@SeyZ  Any idea if this would actually work with findAll()? I get the same error with findAll(), but it works perfect with findOne().

**Comment by SeyZ** [comment]
This library is agnostic. It means that `JSONAPISerializer` expects to have plain JSON in input and produces plain json in output.

Passing something else is unsupported. I don't know the behavior with `findAll()` or `findOne()` in Sequelize.

**Comment by rohanthacker** [comment]
Cheers, wanted to know if you had an eligant solution for it. Thanks again
