### ISSUE TITLE
Support has died. See description.

### ISSUE THREAD

**Issue by jun-sheaf** [SeyZ/jsonapi-serializer#231]
So support for these kind of serialization libraries has died down quite a bit. Moreover, all of them fail to serialize the entire spec...

So over the past few days I've designed a resource-recursive, typescript/javascript library for serializing the entire JSON:API spec. Our API is far more fluent (and obvious) than the one here (and every other serializer I have seen/used). If this serializer doesn't fit your need, you might want to check it out :) Development is active.

If you are in particular struggling with issues such as links, resource relationships, and deep recursion (essentially any of the complicated parts of the JSON:API spec), I **strongly** recommend moving to our library.

{TS:JAPI}: [https://github.com/jun-sheaf/ts-japi](https://github.com/jun-sheaf/ts-japi)

**Comment by saulotoledo** [comment]
@jun-sheaf at first glance your library seems interesting. Just be aware the licence you are using may prevent adoption by commercial software companies.

**Comment by jun-sheaf** [comment]
@saulotoledo Perhaps using the "disclose source" part may be unneeded. I've weakened the license to the standard Apache 2.0 license.
