### ISSUE TITLE
Automatic char conversion

### ISSUE THREAD

**Issue by melkior** [SeyZ/jsonapi-serializer#25]
Hi,

I've got one problem with serialization. Now, if attribute (options) contains '_' ie. underscore character, it will be converted to '-' ie. minus character (inside data). Is this correct behavior, because I'd really like to leave attributes untouched? Anyway ,if you look here:

http://jsonapi.org/format/#document-member-names

it looks like underscore is allowed character.

Thank you very much

**Comment by SeyZ** [comment]
Hi @melkior !

Can you paste me an example of your dataSet with the `_` ? Thanks!

**Comment by melkior** [comment]
Try this:

var data = [{
    id: 1,
    first_name: 'Sandro',
    last_name: 'Munda',
  },{
    id: 2,
    first_name: 'John',
    last_name: 'Doe',
  }];

var JSONAPISerializer = require('jsonapi-serializer');

var users =new JSONAPISerializer('user', data, {
  topLevelLinks: { self: 'http://localhost:3000/api/users' },
  dataLinks: {
    self: function (user) {
      return 'http://localhost:3000/api/users/' + user.id
    }
  },
  attributes: ['first_name', 'last_name']
});

console.log(JSON.stringify(users));

Output:

{"links":{"self":"http://localhost:3000/api/users"},"data":[{"type":"users","id":"1","attributes":{"first-name":"Sandro","last-name":"Munda"},"links":{"self":"http://localhost:3000/api/users/1"}},{"type":"users","id":"2","attributes":{"first-name":"John","last-name":"Doe"},"links":{"self":"http://localhost:3000/api/users/2"}}]}

It will convert first_name/last_name into first-name/last-name.

This conversion is part of dasherize() function, so it would be nice to make it configurable the same way as pluralizeType, and also patch would be just additional check in that function. Anyway, it would be nice to have since specification says nothing about this kind of conversions.

If you are interested I can try to make a change?

Thank you.

**Comment by SeyZ** [comment]
I think you are looking for the `keyForAttribute` option.
Example:

```javascript
var inflection = require('inflection');
      var dataSet = {
        id: '1',
        firstName: 'Sandro',
        lastName: 'Munda',
        books: [{ createdAt: '2015-08-04T06:09:24.864Z' }],
        address: { zipCode: 42912 }
      };

      var json = new JsonApiSerializer('user', dataSet, {
        attributes: ['firstName', 'lastName', 'books', 'address'],
        books: { attributes: ['createdAt'] },
        address: { attributes: ['zipCode'] },
        pluralizeType: false,
        keyForAttribute: function (attribute) {
          return inflection.underscore(attribute);
        }
      });
```

**Comment by melkior** [comment]
Yeah, that's it.

Ok, with one little difference, I just need:

    keyForAttribute: function(attribute) {
        return attribute;
    }

I'll close issue, thank you very much.

**Comment by SeyZ** [comment]
:+1:
