### ISSUE TITLE
Ember expects singularized types for included data in relationships

### ISSUE THREAD

**Issue by wzrdtales** [SeyZ/jsonapi-serializer#26]
... and thus can't properly parse the results.

Given the following example
```json
"relationships": {
      "foobars": {
        "data": [
          {
            "type": "foobars",
            "id": "1"
          },
          {
            "type": "foobars",
            "id": "2"
          },
          {
            "type": "foobars",
            "id": "3"
          }
        ]
      }
    }
  },
"included": [
    {
      "type": "foobars",
      "id": "1",
      "attributes": {
        "foo": "barbor",
        "delete-id": 0
      }
    },
    {
      "type": "foobars",
      "id": "2",
      "attributes": {
        "foo": "barbar",
        "bar": 1
      }
    },
    {
      "type": "foobars",
      "id": "3",
      "attributes": {
        "foo": "barber",
        "bar": 2
      }
    }
  ]
}
```

This should be instead:

```json
"relationships": {
      "foobars": {
        "data": [
          {
            "type": "foobars",
            "id": "1"
          },
          {
            "type": "foobars",
            "id": "2"
          },
          {
            "type": "foobars",
            "id": "3"
          }
        ]
      }
    }
  },
"included": [
    {
      "type": "foobar",
      "id": "1",
      "attributes": {
        "foo": "barbor",
        "delete-id": 0
      }
    },
    {
      "type": "foobar",
      "id": "2",
      "attributes": {
        "foo": "barbar",
        "bar": 1
      }
    },
    {
      "type": "foobar",
      "id": "3",
      "attributes": {
        "foo": "barber",
        "bar": 2
      }
    }
  ]
}
```
### The Problem

Actually it is only possible to specify the typeForAttribute option, and thus it is not possible to specify them for nested or compound attributes. Maybe we also need a singularize optionality?

Note: This seems to be intended, but yet undocumented https://github.com/emberjs/data/issues/3687

**Comment by SeyZ** [comment]
I use Ember too. I can't reproduce the problem you describe.
I think you need to have the same type in the `relationships` and the `included` entries. You need to be consistent.

I'm not sure Ember has a problem to "parse" pluralized type as you describe.

If your problem persists, can you paste here a [JSBin](https://emberjs.jsbin.com/) to reproduce it?

Thanks!

**Comment by wzrdtales** [comment]
Actually you're right, I just discovered that the problem at this time seems that it was something else. I wasn't able to reproduce the behavior described above again. Ember-data does resolve the fields now correctly and I'm not sure what was wrong exactly I try to figure this out, but for now this can be closed.

Thank you for your time!

**Comment by SeyZ** [comment]
:+1:
