### ISSUE TITLE
Differing collection name from type

### ISSUE THREAD

**Issue by digitalsadhu** [SeyZ/jsonapi-serializer#31]
If I have:

``` js
// GET /users/1
{
  data: {
    type: 'users',
    id: 1,
    attributes: {
      name: 'Charles',
      ...
    },
    relationships: {
      friends: {
        data: [
          { id: 2, type: 'users' },
          { id: 3, type: 'users' }
        ]
      }
    }
  }
}
```

In my dataset `friends` is actually type `users`. It doesn't seem possible to tell jsonapi-serializer this. Is this correct? 

A use case I see is if I am using the model `user` for 2 relationships. 1 called `contractors` and one called `clients`

Great library, thanks! Saving me a tonne of time/effort!

**UPDATE** Improved the json example above for clarity

**Comment by SeyZ** [comment]
Hey @digitalsadhu ! Could you provide me your dataSet to improve your example? I think it's possible but I need it to be sure ;)

So cool that my library saves you a lot of time/effort :+1:

**Comment by digitalsadhu** [comment]
Great thanks for the response!

Will probably take me a few days but I'll put something together and post. 

Cheers!

**Comment by digitalsadhu** [comment]
Maybe this doc from the JSON API website can highlight the use case I'm describing:

```json
{
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "links": {
      "self": "http://example.com/articles/1"
    },
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      },
      "comments": {
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments"
        },
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    }
  }],
  "included": [{
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
  }, {
    "type": "comments",
    "id": "5",
    "attributes": {
      "body": "First!"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "2" }
      }
    },
    "links": {
      "self": "http://example.com/comments/5"
    }
  }, {
    "type": "comments",
    "id": "12",
    "attributes": {
      "body": "I like XML better"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "9" }
      }
    },
    "links": {
      "self": "http://example.com/comments/12"
    }
  }]
}
```

The relationship is `author` but the `type` is `people`

**Comment by jamesdixon** [comment]
I haven't personally tried this, but assuming this should be as simple as allowing a `type` attribute to be specified for `relationshipLinks` that would ultimately override the `type` passed into the serializer?

**Comment by bilherron** [comment]
I had this same issue, here's a solution. In the options object passed to the serializer add a `keyForAttribute` function that can check for your property name and return the correct type. For the original example above it would look something like this:

```
serializerOpts = {
  typeForAttribute: function(str) {
    if (str === 'friends') {
      return 'users';
    }
    return undefined;
  }
}
```

(Returning undefined allows the default `getType` operation to continue.)

Hope that helps!
