### ISSUE TITLE
Relationships without data

### ISSUE THREAD

**Issue by aalimovs** [SeyZ/jsonapi-serializer#34]
Hi,

I'm serializing a mongoose model, which works great. Im after adding a relationship, that is not in the original model. 

The relationship returned should be without resource linkage (data) and provide only links(as is allowed by the specification), so that the end result would look like this:

```javascript
{
    "type": "users",
    "id": "1",
    "attributes": {
        "name": "John"
    },
    "relationships": {
        "notes": {
            "links": {
                "related": "http://localhost/users/1/notes"
            }
        }
    }
}
```

However, as I understand you currently cannot declare a relationship links without attribute being present in the model?

**Comment by SeyZ** [comment]
Indeed, to have this kind of result, the original data must be something like this:

```
{ "id": "1", "name": "john", "notes": [ ... ] }
```

In your mongoose model, if you don't have the relationship between these collections, you have to "preprocess" your json before passing it through the `jsonapi-serializer`.

For example:

```
User.findById(1).lean.exec(function (err, user) {
  user.notes = // ... ... ...

  var json = new JsonApiSerializer('users', user, {
    ...
  });
});
```

**Comment by aalimovs** [comment]
The issue then is, there's data object present in the relationship, which shouldn't be there if we want it to be a link only. So it becomes sort of a hack, have to "preprocess" to add notes, then "postprocess" to delete data from serialized data.relationships.notes.data. If it's a collection of items, becomes more messy.

What about adding new options when defining attributes? 

One for attribute not to have data (useful if it exists in the model, but for whatever reason want to have a links only for it).

And second one, being able to define attributes that are not in the model?

**Comment by jamesdixon** [comment]
Any other thoughts on how to resolve this? I'm now running into the same issue.

**Comment by jamesdixon** [comment]
@SeyZ I recall you saying that you use Ember. Are you setting all of your Ember Data models to not use async relationships and just have all of your relations returned as a compound document? If not, I'd imagine you'd be running into this issue as well.

**Comment by SeyZ** [comment]
Hey @jamesdixon Sorry for the delay!

I introduced the `ignoreRelationshipData` option. Is it what you want?
The "doc" is in the README:

    ignoreRelationshipData: Do not include the data key inside the relationship. Default: false.

**Comment by jamesdixon** [comment]
Hey @SeyZ - no worries!

I actually did give that a shot, but it wasn't working for me. I'll give it another go and see if I can't get it to function.

**Comment by SeyZ** [comment]
If it does not work. Maybe it would be efficient to describe in a nutshell
- Your data input
- The serializer options you are using
- The current result
- The expected result
