### ISSUE TITLE
Bookshelf?

### ISSUE THREAD

**Issue by jamesdixon** [SeyZ/jsonapi-serializer#35]
@SeyZ I noticed in one of your other posts that you're using Ember on the front-end. By any chance are you using Bookshelf as your ORM on the backend?

**Comment by SeyZ** [comment]
Hey @jamesdixon ! Yeah, I often use Ember :+1: 

I already used Bookshelf on my backend. What's your question?

**Comment by jamesdixon** [comment]
Awesome :+1: I was just curious how you handled using the serializer to convert your Bookshelf models to JSON API for Ember to consume?

**Comment by SeyZ** [comment]
I never pass Bookshelf (or Sequelize, or Mongoose, etc.) models to the `jsonapi-serializer`. Before passing the payload to serialize, I just call the `toJSON` method on the object: http://bookshelfjs.org/#Model-instance-toJSON

**Comment by jamesdixon** [comment]
Yeah, I'm basically doing the same thing. The one thing I did do was write a method that will build the proper options for the `jsonapi-serializer` rather than having to do each model manually.

**Comment by jamesdixon** [comment]
Thanks :) Was just curious as to how others are doing it :)

**Comment by SeyZ** [comment]
:+1:
