### ISSUE TITLE
One-to Included relationships Incorrect when the relationship isn't defined

### ISSUE THREAD

**Issue by jamesdixon** [SeyZ/jsonapi-serializer#36]
When including a one-to relationship in a compound document and that relationship isn't defined, [according to the spec](http://jsonapi.org/format/#fetching-resources-responses-200), it should return a `null` `data` attribute. Currently, if the relationship exists, but isn't defined, I get an incorrect response. For example, say there is a `staff` relationship on an `appointment` model. If the `appointment` has an undefined `staff_id`, I get the following:

```javascript
      "relationships": {
        "staff": {
          "data": {
           "type": "staff",
           "id": "undefined"
         }}}
```

Unless I'm reading the spec wrong, I believe it should be:

```javascript
      "relationships": {
        "staff": {
          "data": null
        }}
```

I've already whipped up a PR, but wanted to run this by you first. I believe it's different than #34, which is why I opened a new issue.

Thanks, as always, for the the great work!

James

**Comment by SeyZ** [comment]
Awesome @jamesdixon ! If you're still ok, I'm waiting to review your PR. Thanks very much!

**Comment by SeyZ** [comment]
Ok, didn't see the PR. I'm reviewing it :)
