### ISSUE TITLE
Test creating invalid JSON API result?

### ISSUE THREAD

**Issue by sarus** [SeyZ/jsonapi-serializer#38]
I just updated to v2.0.4 (from the 1x branch) and a lot of my tests are breaking now.  I noticed the following test in jsonapi-serializer that appears to be creating an invalid json payload:

https://github.com/SeyZ/jsonapi-serializer/blob/master/test/serializer.js#L958

The test is testing a top level links object for a single resource.  My understanding based on the JSON API 1.0 specification is that the `links.self` attribute should point back to the single resource rather than the collection of resources.  

Here is the example given on the json api website:

```
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "http://example.com/articles/1" // <-- Notice the link is to the specific resource
  },
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "author": {
        "links": {
          "related": "http://example.com/articles/1/author"
        }
      }
    }
  }
}
```

In your test however, you are creating a self link that points to the resource collection rather than the resource object.  Here is the test right now:

```
  describe('Top level links with a single resource', function () {
    it('should be set', function (done) {
      var dataSet = {
        id: '54735750e16638ba1eee59cb',
        firstName: 'Sandro',
        lastName: 'Munda',
      };

      var json = new JsonApiSerializer('users', dataSet, {
        topLevelLinks: {
          self: 'http://localhost:3000/api/users'
        },
        attributes: ['firstName', 'lastName'],
      });

      expect(json).to.have.property('links').eql({
        self: 'http://localhost:3000/api/users'
      });

      done(null, json);
    });
  });
```

To be valid JSON-API shouldn't the test condition be:

```
      expect(json).to.have.property('links').eql({
        self: 'http://localhost:3000/api/users/54735750e16638ba1eee59cb'
      });
```

While the test as written passes it appears to be validating an invalid json api document.  I think it would be better if the tests created and tested valid JSON-API payloads to help provide a second source of documentation for users of this library.  

Apologies If I'm misunderstanding the JSON API specification which is definitely possible!

**Comment by jamesdixon** [comment]
@sarus you're correct. I'm sure @SeyZ would gladly accept a PR! The test should probably be something like this:

```javascript
  describe('Top level links with a single resource', function () {
    it('should be set', function (done) {
      var dataSet = {
        id: '54735750e16638ba1eee59cb',
        firstName: 'Sandro',
        lastName: 'Munda',
      };

      var json = new JsonApiSerializer('users', dataSet, {
        topLevelLinks: {
          self: function(data) {
            return 'http://localhost:3000/api/users/' + data.id;
          }
        },
        attributes: ['firstName', 'lastName'],
      });

      expect(json).to.have.property('links').eql({
        self: 'http://localhost:3000/api/users/' + dataSet.id
      });

      done(null, json);
    });
  });
```

That said, you mentioned your tests breaking. Was this issue purely about the test or issues with your code breaking?

**Comment by sarus** [comment]
@jamesdixon My tests were breaking because I think there must have been a bug in the older version of json-api serializer I was using where no top level links property was being created.  Now the top level links property is being properly created but I wasn't testing for that.  So basically I think I was passing my tests because my tests were testing for invalid json-api.  (The short answer is this issue is just for the test)

So my old json payload using `v1.0` looked like:

```
{ 
   data:
   { 
      type: 'users',
      id: '5',
      attributes:
      { 
         username: 'newuser',
         email: 'newuser@localhost.com',
         'full-name': 'New User' 
       },
       links: { self: 'https://dev.breach/v1/users/5' } 
   } 
}
```

When I switched to `v2.0` the top level links property was created and the payload became:

```
{ 
   links: { self: 'https://dev.breach/v1/users/5' } },
   data:
   { 
      type: 'users',
      id: '5',
      attributes:
      { 
         username: 'newuser',
         email: 'newuser@localhost.com',
         'full-name': 'New User' 
       },
       links: { self: 'https://dev.breach/v1/users/5' } 
   } 
}
```

This of course broke my tests so I started looking into it and ran across the tests in the json-api library.  While a bit redundant I'm assuming it's still valid JSON-API to have a top level links property and a data level links property for a single resource.

Do you know if that's the case?  If not then I think I just need to drop the dataLinks section for single resources.

I'll put together a PR to change the test.

**Comment by jamesdixon** [comment]
@sarus makes complete sense!

As for the redundant link, I ran into the same thing as it wasn't clear in the spec. I ended up with the format you used when using 1.0. I'm not sure what's actually "correct," but I think you're right in that it's still valid JSON API.

**Comment by SeyZ** [comment]
Yes, it makes sense @sarus. Thanks guys @sarus and @jamesdixon !

**Comment by SeyZ** [comment]
PR merged. Reopen the issue if it still a problem.
