### ISSUE TITLE
Duplicate includes

### ISSUE THREAD

**Issue by xbill82** [SeyZ/jsonapi-serializer#4]
Hi,
I found out that, when serializing an array of objects related to one same resource (e.g. many `Articles` written by the same `Author`), that resource is duplicated many times in the `included` array.

I'll try to solve this and submit a Pull Request when I get a moment.

**Comment by SeyZ** [comment]
@xbill82 I think I already fixed this issue in the master branch

**Comment by xbill82** [comment]
Ok, 2 things here

* when installing the lib from `npm` I don't get the latest version of the code (baybe due to the missing `repository` field in `package.json`?)
* I still got the problem. I'll try to debug this out when I get a sec.

**Comment by SeyZ** [comment]
@xbill82 Ok I bump the version `1.0.2`. It's available from npm registry now.
Can you test if you still have the issue with the new version `1.0.2`?

**Comment by xbill82** [comment]
@SeyZ Yep! It actually works! Gread job!

**Comment by SeyZ** [comment]
:+1:
