### ISSUE TITLE
Serialize To One relationship

### ISSUE THREAD

**Issue by sescobb27** [SeyZ/jsonapi-serializer#41]
Hi, I'm having the following issue
I have this serializer
```js
var JSONAPISerializer = require('jsonapi-serializer');
var _ = require('lodash');

module.exports = function CustomerSerializer(data) {
  this.serialize = () => {
    return new JSONAPISerializer('customers', data, {
      topLevelLinks: {
        self: (body) => '/customers' + (_.isArray(body) ? '' : '/' + body.id)
      },
      dataLinks: {
        self: (customer) => '/customers/' + customer.id
      },
      attributes: [
        ...,
        'orders',
        'plan'
      ],
      plan: {
        ref: 'id',
        included: false,
        relationshipLinks: {
          self: (customer) => '/customers/' + customer.id + '/relationships/plan'
        },
        attributes: []
      },
      orders: {
        ref: (_, item) => item,
        included: false,
        relationshipLinks: {
          self: (customer) => '/customers/' + customer.id + '/relationships/orders'
        },
        attributes: []
      },
    });
  };
};
```
but the data's `plan` attribute I'm passing to serializer is an already plain string e.g
```json
{ "plan": "UUID-STRING" }
```
but in the response, `plan` is kept in attributes hash, instead of in relationships, I think the issue is here https://github.com/SeyZ/jsonapi-serializer/blob/master/lib/serializer-utils.js#L122 because you are making an assumption that relationships comes in `Object`s or `Array`s, for example if you take a look in `orders`  hash I'm doing `ref: (_, item) => item` because `orders` attribute is an Array of `String`s

**Comment by SeyZ** [comment]
Hey @sescobb27 ! I need to reproduce easily your issue. Could you provide me:

- Data input
- JSON serializer options
- Expected result
- Current result

Then, I will try to fix it :+1:

**Comment by sescobb27** [comment]
Hi @SeyZ I already solved id here https://github.com/sescobb27/jsonapi-serializer/commit/88ca5ea93fa7130886ea1c999865511551c61113 that commit it's inside the PR for JSON API deserializer https://github.com/SeyZ/jsonapi-serializer/pull/43

**Comment by SeyZ** [comment]
Awesome @sescobb27 ! Can you `cherry-pick` your commit and make a pull request? Thanks!

**Comment by sescobb27** [comment]
@SeyZ https://github.com/SeyZ/jsonapi-serializer/pull/45 done :)

**Comment by pwalczyszyn** [comment]
:+1: I'm seeing similar problem with To-One relationship. In my case value of the attribute is an object which I would like to be referenced in the `relationships` instead `attributes`.

**Comment by pwalczyszyn** [comment]
I found what was causing my problem. The models returned from my ORM mapper ([objection.js](http://vincit.github.io/objection.js)) are not plain objects according to `_.isPlainObject()` function. That is why my related object wasn't referenced as a `relationships`. Why do need to check if object is plain object in this case?

This is the line of code that is using `_.isPlainObject()` function. 
https://github.com/SeyZ/jsonapi-serializer/blob/master/lib/serializer-utils.js#L84

**Comment by SeyZ** [comment]
Hey @pwalczyszyn ! Indeed, jsonapi-serializer is ORM/Framework agnostic. We only support plain JS data.

`isComplexType` function uses "isPlainObject()" to ensure the type is a plain JS Object `{}` and a `Date` for example.

**Comment by sescobb27** [comment]
@SeyZ @pwalczyszyn i already solved that issue with https://github.com/SeyZ/jsonapi-serializer/pull/45 but don't know if that apply to your case cause the object is with a specific ORM, what i'm doing right now with mongoose is this
```js
'use strict';
var JSONAPISerializer = require('jsonapi-serializer').Serializer;
var _ = require('lodash');
var mongoose = require('mongoose');

module.exports = function OrdersSerializer(data) {
  this.serialize = () => {
    return new JSONAPISerializer('orders', data, {
      topLevelLinks: {
        self: (body) => '/orders' + ((_.isArray(body) || !body.id) ? '' : `/${body.id}`)
      },
      dataLinks: {
        self: (order) => `/orders/${order.id}`
      },
      attributes: [
        'details'
      ],
      typeForAttribute: (attr) => {
        if (attr === 'details') {
          return 'order-details';
        }
        return attr;
      },
      details: {
        ref: (__, item) => {
          // item could be an MongoDB ObjectId, a MongoDB BSON type with toHexString
          // function, a MongoDB populated Object with id attribute or a plain String
          if (item instanceof mongoose.Types.ObjectId) {
            return item.toString();
          } else if (item && _.isFunction(item.toHexString)) {
            return item;
          } else if (item && item.id) {
            return item.id;
          }
          return item;
        },
        relationshipLinks: {
          self: (order) => `/orders/${order.id}/relationships/details`
        }
      }
    });
  };
};
```
