### ISSUE TITLE
RFC: JSONAPIDeSerializer

### ISSUE THREAD

**Issue by sescobb27** [SeyZ/jsonapi-serializer#42]
Hi, I'm running an express backend application and I'm using this lib, but it doesn't Deserialize JSONAPI request payloads to construct functional Objects, so in order to do that, I'm making this RFC so we can have an starter point. thanks :)
```js
'use strict';
var _ = require('lodash');
var inflection = require('inflection');
var SerializerUtils = require('./serializer-utils');

// {
//   "data": {
//     "attributes": {
//       "order-type": "subscription",
//       "production-state": "0",
//       "payment-state": "0",
//       "shipment-state": "0",
//       "created-at": null,
//       "ship-date": null,
//       "season": "FA15"
//     },
//     "relationships": {
//       "plan": {
//         "data": {
//           "type": "plans",
//           "id": "1-shirt"
//         }
//       },
//       "coupon": {
//         "data": null
//       },
//       "address": {
//         "data": null
//       },
//       "customer": {
//         "data": null
//       }
//     },
//     "type": "orders"
//   }
// }

var DeSerializer = new SerializerUtils('', null, null, {
  keyForAttribute: 'CamelCase'
});

module.exports = function (collectionName, payload) {
  var attributes = payload.data.attributes;
  var relationships = payload.data.relationships;

  var relations = Object.keys(relationships);
  var collectionAttrs = {};
  Object.keys(attributes).forEach(function (key) {
    collectionAttrs[_.camelCase(key)] = _.clone(attributes[key], true);
  });
  var collection = new collectionName(collectionAttrs);
  // console.log('COLLECTION: ', attributes);

  relations.forEach(function (relation) {
    // (e.g 1)
    // "relationships": {
    //   "plan": {
    //     "data": {
    //       "type": "plans",
    //       "id": "1-shirt"
    //     }
    //   }
    // }
    // (e.g 2)
    // "relationships": {
    //   "coupon": {
    //     "data": null
    //   }
    // }
    var relationshipPayload = relationships[relation];
    var relationshipData = relationshipPayload.data;
    // relationType => Plan
    if (!relationshipData) {
      return;
    }
    if (_.isArray(relationshipData)) {
      // TODO:
      // Order.products = [Product.new(...), Product.new(...), Product.new(...)];
      collection[_.camelCase(relation)] = _.map(relationshipData, function (relationData) {
        return _.omit(relationData, 'type');
      });
    } else {
      // Plan.new({ id: '1-shirt' });
      var relationObject = _.omit(relationshipData, 'type');
      // Order.plan = Plan.new({ id: '1-shirt' });
      collection[_.camelCase(relation)] = relationObject;
    }
  });
  return collection;
};

// var newOrder = JSONAPIDeSerializer(Order, req.body);
```

**Comment by sescobb27** [comment]
![screen shot 2015-10-21 at 3 39 40 pm](https://cloud.githubusercontent.com/assets/1157892/10650825/57c462b6-7811-11e5-877b-fc065552c075.png)

**Comment by sarus** [comment]
Seems like it would be a neat addition to be able to go both ways.  Is the idea here to take a json api payload and turn it back into the original denormalized input data?  

I assume the use case here is in the browser if you're not using something like Ember Data?

**Comment by sescobb27** [comment]
yeah, I made this PR https://github.com/SeyZ/jsonapi-serializer/pull/43, the idea is to deserialize the payload into plain JS objects from a Req/Res payload body

**Comment by SeyZ** [comment]
Hey @sescobb27, thanks for your idea!

`jsonapi-serializer` aims to be totally framework agnostic, and I'm not sure the deserialization stuff can be agnostic. When you deserialize a relationship (e.g. a `Plan`), you expect to have a Plan object (Mongoose model, sequelize model or whatever).

**Comment by sescobb27** [comment]
Yeah you are right but at this moment we can return a plain JS Object and let the user handle framework's specific logic, for example, I'm using the fork I made and it works pretty well, the only thing I run after `DeSerialize` is a normalization step to handle relationships. why? because it should be agnostic but I want to DRY my code as much as I can in order to reuse serialization/deserialization stuff and is easier, at least for me, to adapt a plain nested JS object than a JSON API payload

**Comment by sescobb27** [comment]
https://gist.github.com/sescobb27/ce0bbe86db395f1464cc

**Comment by SeyZ** [comment]
Awesome @sescobb27 Thanks for the hard work!

I have an application that uses jsonapi-serializer. For now, I handle the deserialization without this library, by hand. It's a good idea to improve that!

I'll use your branch in my project and I'll give you my feedback.
Thanks again!

**Comment by SeyZ** [comment]
The deserializer part is now on master. Documentation will be available soon. Meanwhile, check the tests ;-)
