### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by brettneese** [SeyZ/jsonapi-serializer#44]
Related to #13, I'm going to fork this library to add in proper error object support in order to conform with JSON API's standards on throwing errors.

Anything in particular I should be aware of/attempt to implement while I'm at it?  

I'm not planning on parsing error codes and such within jsonapi-serializer - just properly handling a supplied error object. My biggest question is whether I should add an `err` (like `JSONAPISerializer(type, data, opts, err)`) or magically parse a supplied `error` type, or include it in `opts` ala `meta`, or something else? (Could also add a `JSONAPISerializer.error(type, data, opts)`). 

I know part of the goal with jsonapi-serializer is to be as agnostic as possible and I plan on submitting a PR when I'm done so any thoughts on best practices as I work on this would be appreciated.  :)

**Comment by SeyZ** [comment]
Awesome @brettneese ! I can't wait your PR :+1: 

I think passing an option (`isError: true`?) to the opts can be used. I don't have a strong opinion, so maybe you prefer another way?

Thanks again!

**Comment by brettneese** [comment]
Since per jsonapi standards, you cannot have a response with both a "data" and "errors" object, I decided to magically treat any supplied "error" or "errors" collection/resource as an error and parse it from there, so you can just JSONApiSerializer('error', errorData) and it will spit out the appropriate response. 

I haven't finished implementing all the `opts` yet (only `meta` and `topLevelLinks` -- I'm currently just doing `payload.errors.push(records)` instead of something like ErrorSerliazerUtils()).)  When I get that done, I'll do a PR, but it might be a few more days because we actually don't need any of the other options. https://github.com/brettneese/jsonapi-serializer

**Comment by nahtnam** [comment]
Would love this. Currently doing it by hand in my application.

**Comment by mikejerome** [comment]
:+1: I would like to see this as well.

**Comment by john-goldsmith** [comment]
Any updates here?

**Comment by mariogintili** [comment]
Would love to have this too!

**Comment by SeyZ** [comment]
@mariogintili @john-goldsmith @mikejerome @ghost @brettneese 

The feature is now available and documented on the README. Don't hesitate to share your feedback ;)
