### ISSUE TITLE
Doesn't handle being passed mongoose models well.

### ISSUE THREAD

**Issue by awochna** [SeyZ/jsonapi-serializer#52]
I've encountered an issue where I'm trying to serialize a mongodb document and using mongoose as my ODM. I need my server to output the information using JSON API.

When testing the the serializer's output with some of my mongoose documents as input, I get an empty attribute object. Using raw JSON gives the right output.

I know this seems like it has to do with how mongoose represents document objects internally, but I found the solution in how this module attempts to access attributes for the passed record.

I'll be submitting a pull request that should fix this soon!

**Comment by jamesdixon** [comment]
@awochna I'll let @SeyZ give you the final word on this, but my opinion is that serializing Mongoose models directly is out of the scope of this project. The serializer is meant to be ORM-agnostic and simply converts raw JSON to JSON API using a set of transform options.

That said, my project [oh-my-jsonapi](https://github.com/jamesdixon/oh-my-jsonapi), is meant to do exactly what you're referencing. It's built on top of this project and uses ORM-specific adapters to generate the necessary options to pass to the serializer. Currently, there is no Mongoose adapter (only Bookshelf), but it would be great if you'd be willing to submit a PR to add a Mongoose adapter.

Cheers.

**Comment by awochna** [comment]
Thanks @jamedixon. I'm currently using my repository (with the changes in the above pull request) for now. Your project looks interesting, and if my PR gets rejected, I'll look at switching.

The fact that the serializer doesn't work well with Mongoose models is the symptom that I'm reporting in this issue, but the fix for this issue is to iterate through the passed attributes that should be allowed and checking for them in the data object, instead of the other way around. This should prove to have the same behavior in other cases.

**Comment by jamesdixon** [comment]
@awochna when you say that the serializer doesn't work well with Mongoose models, are you attempting to pass the model directly to the serializer?

**Comment by awochna** [comment]
Yes. Let me explain.

When I have a mongoose model and call `console.log()` passing it in, I get a printed object that contains the attributes I expect, plus 2 more(_id and _v). I don't need to know that these attributes don't actually live in my object (but in a sub-object) and so using the model object feels very intuitive because all of the ODM stuff is abstracted away. __I ask the object for it's attributes and it gives them to me.__ This is a common thing in Object Oriented Development because we send the object a message requesting an attribute and give it the opportunity to respond with something completely different.

The current version of this utility takes an object and then dumps all of it's keys. It doesn't ask the object anything or send any messages. If the attributes to keep are in the key-dump, it'll ask the object for the value for that key. This filters out any delegated messages or overrides.

Instead, my change (which then provides support for this style of OO programming, including objects like those produced by Mongoose) asks the object for the value of each of the attributes. This gives it the chance to delegate and everything continues to work in a way that is abstracted from the end developer. Everything is intuitive again.

I hope that helps and let me know if anything isn't clear.

**Comment by SeyZ** [comment]
Merged. Thanks @awochna good job!

**Comment by jamesdixon** [comment]
@awochna sorry, completely forgot to respond to your previous post. Yes, after reading what you said, it made much more sense, especially when it became clear that it was less about Mongoose models specifically and more about the approach to retrieving that object's attributes.  Cheers!
