### ISSUE TITLE
Filtering Attribute for Object

### ISSUE THREAD

**Issue by jylinman** [SeyZ/jsonapi-serializer#54]
Hey there,

I think we should be able to still specify if the object can still be filtered out by `attributes` settings even if its not a compound document or something... For example, I have settings like this:

```js
{
    attributes: ['status', 'roles']
    roles: {
        attributes: ['name']
    }
}
```

However, when an `opts` setting does not include `ref:` as seen on line [#128](https://github.com/SeyZ/jsonapi-serializer/blob/master/lib/serializer-utils.js#L128) then the response will look like this still (unfiltered):

```js
{
  "data": {
    "type": "users",
    "id": "7fb4a2bd-a30c-4b9a-a15b-f9a13ed0ffca",
    "attributes": {
      "status": "active",
      "roles": [
        {
          "id": 245,
          "name": "sysadmin",
          "userId": 216,
          "updatedAt": "2016-01-18T12:53:36.000Z",
          "createdAt": "2016-01-18T12:53:36.000Z"
        }
      ]
    }
  }
}
```

Do you think we can work this into it?

**Comment by SeyZ** [comment]
Hey @jylinman ! I think your issue refers exactly #48 
I have fixed the problem in the fix-48 (https://github.com/SeyZ/jsonapi-serializer/tree/fix-48) branch. Can you tell me if it's ok?

I will merge soon the branch to the master ;)

**Comment by jylinman** [comment]
Looks like that does it ;) Thanks for doing that.
