### ISSUE TITLE
Creating Nested Resources 

### ISSUE THREAD

**Issue by erikakers** [SeyZ/jsonapi-serializer#56]
This could be more of a question, however I've dug through all of the issues and the source code and I can't find the answer. 

I've got a simple person object that is returned from a model: 

```
{ 
  id: 1,
  firstName: 'John',
  lastName: 'Smith',
  homeTown: 'Smallville',
  homeState: 'KS'
}
```

I would like to homeTown and homeState to be nested in the return object like this:

```
{
  "links": {
    "self": "..."
  },
  "meta": {
    "updated": "2016-01-25T00:00:00.000Z"
  },
  "data": {
    "type": "person",
    "id": "1",
    "attributes": {
      "FirstName": John",
      "LastName": "Smith",
      "Home": {
        "HomeTown": "Smallville",
        "HomeState": "KS"
      }
    }
  }
}
```

So reading through the documentation and based on search around I expected this would return that result:

```
const response = new API('players', model, {
  keyForAttribute: 'CamelCase',
  topLevelLinks: {
    self: req.protocol + '://' + req.hostname + req.path
  },
  attributes: ['firstName', 'lastName', 'home'],
  home: {
    attributes: ['homeTown', 'homeState']
  }
});

res.json(response);
```

But that doesn't return the home object and only the firstName and lastName fields.

**Comment by SeyZ** [comment]
Check https://github.com/SeyZ/jsonapi-serializer/pull/57#issuecomment-290880799
