### ISSUE TITLE
Deserializer without included member

### ISSUE THREAD

**Issue by Aurelsicoko** [SeyZ/jsonapi-serializer#58]
I think the deserializer always try to find an `included` member on the root object. I read the specifications again and we can send a reference directly in the relationships member such as the example below. 

Dataset (POST request)
```json
{
  "data": {
    "type": "article",
    "attributes": {
      "title": "My first title",
    },
    "relationships": {
      "contributors": {
        "data": [{"type":"user", "id": "1"}]
      }
    }
  }
}
```

Returned
```
{
  title: 'My first title',
  id: undefined,
  contributors: [ null ] 
}
```

Excepted
```
{
  title: 'My first title',
  contributors: [ '1' ] 
}
```

**Comment by SeyZ** [comment]
Hey @Aurelsicoko 

Thanks for the clarity of your issue. I appreciate :) You're right, if there's no include, the relationship value is considered as `null`. However, you can still use the `valueForRelationship` option to control the value you want instead. For example:

```
new JSONAPIDeserializer({
  user: {  // the type of the relationship
    valueForRelationship: function (relationship) {
      return relationship.id; // here's I return the ID but you can return anything you want (with a database query for example)
    }
  }
}).deserialize(dataSet, function (err, json) {
  // ...
});
```

The result will be:

```
{ title: 'My first title', id: undefined, contributors: [ '1' ] }
```

**Comment by SeyZ** [comment]
Reopen the issue if you still have the issue.

**Comment by danielebriggi** [comment]
Why is not included by default the relationship's id? 
```
{ 
    title: 'My first title', 
    ...,
    contributors: { 
        id: '1' 
     }
}
```

**Comment by TMiguelT** [comment]
Sadly this issue still hasn't been fixed. I'd be happy to write a PR to solve it but I don't think it would be merged. In the meantime, here's a slightly hacky workaround that uses a `Proxy` to transform every relationship into an object of the form `{id: 1}`: https://gist.github.com/TMiguelT/9a76026da1295fbb864754abfc87ed65
