### ISSUE TITLE
Attribute with false value is not being added to attributes

### ISSUE THREAD

**Issue by zenoplex** [SeyZ/jsonapi-serializer#59]
Seems like false values are being ignored in latest version.

```js
new Serializer('test', { foo: false }, { attributes: ['foo'] });

// output
{ 
  data: { 
    id: undefined,
    type: 'test',
    // missing attributes
  }
}
```
Same for any falsy values such as `0`.

The npm version which is same 2.0.4 (Released 2015-10-16T12:25:03.617Z) works fine with above examples.

**Comment by SeyZ** [comment]
Hey @zenoplex Thanks for report. I will check this as soon as possible and I let you know ;)

**Comment by SeyZ** [comment]
Hey @zenoplex Thanks for the report and the PR. The #64 fixes the problem a little bit better ;-)
