### ISSUE TITLE
Promises in Deserializer

### ISSUE THREAD

**Issue by Schoonology** [SeyZ/jsonapi-serializer#62]
I couldn't find an existing discussion of the design, but I was wondering the motivations behind using Promises in the Deserialization API. It looks like it was used for serialization as well, but removed in #17 - why the reversal?

Thanks!

**Comment by Schoonology** [comment]
(On an unrelated note, it looks like callbacks are "required" though a Promise is returned. If you don't provide a callback, it tries to call it anyway and throws. :confused:

**Comment by Schoonology** [comment]
And now that I've gotten this code _working_, I see it only calls the callback with the result, no longer resolving the returned Promise.

Also, I know I'm using yet-unreleased code, so it's entirely within your rights to dismiss me as the rando I am and say "we're working on it". :smile:

**Comment by SeyZ** [comment]
Hey @Schoonology 

The Deserialization API uses async stuff because the `valueForRelationship` option allows users query the Database (async query) to retrieve a the value for the current relationship to deserialize.

+1 for the fix of the "callback required"

**Comment by Schoonology** [comment]
In that case, would it be possible to make Promise usage consistent between serialization and deserialization? I understand it would be a major change to the API.

**Comment by pwalczyszyn** [comment]
:+1: for the consistent usage of promises. Also I would suggest dropping `bluebird` dependency as it adds a lot of weight (kB) and use default Promises API. For older browsers support I would suggest a polyfill in README.

**Comment by bttf** [comment]
I think coupling async DB query stuff to deserialization as a whole brings about using promises un-needingly. Wouldn't it be better to have serialization and deserializations both sync by default (since they are fast operations anyway) and leave things like `valueForRelationship` to the implementer to implement on their own?

**Comment by SeyZ** [comment]
Hey guys, FYI bluebird has been removed :) It now uses the default node Promise object instead.
