### ISSUE TITLE
No documentation for breaking changes between 2.0.x and 2.1.0

### ISSUE THREAD

**Issue by tonylukasavage** [SeyZ/jsonapi-serializer#63]
The API for this module has changed entirely in a non-backwards compatible way in 2.1.0. I'm sure I'm not the only greeted by `JSONAPISerializer is not a function` this morning.

It would be beneficial to other developers using this module to know, from the main README.md, that the API changed in 2.1.0 and will break any code prior to 2.1.0.

**Comment by tonylukasavage** [comment]
Additionally, the wiki is also out-of-date, citing the 2.0 API as how to use the 2.x API.

**Comment by SeyZ** [comment]
The migration guide is available on the release https://github.com/SeyZ/jsonapi-serializer/releases/tag/2.1.0

**Comment by SeyZ** [comment]
Done :) https://github.com/SeyZ/jsonapi-serializer/wiki/Migrate-from-2.0-to-2.1 (link available from the README).

**Comment by 4storia** [comment]
Is it possible to also move this API change to 3.0 (and remove 2.1)? As per semantic versioning, minor versions should not introduce breaking changes. Its a little aggravating when deployments break because of minor version bumps (take minor, or `^`, is the default option for `npm install --save`)

**Comment by andjosh** [comment]
Amen

**Comment by SeyZ** [comment]
Sorry guys, you're right

**Comment by 4storia** [comment]
All good man, thanks for updating the version number :D
