### ISSUE TITLE
README should have some documentation on the new Deserializer

### ISSUE THREAD

**Issue by awochna** [SeyZ/jsonapi-serializer#65]
The title makes it pretty self-explanatory, I think. I'm excited about this feature because I've reached a stage in my project where I need to consume information from the outside, and I really like not having to add another library for deserialization.

Unfortunately, I had to do some digging to find out that this library can do that and I have to do some experimenting to figure out how!

I might be able to submit a PR for this, but if someone else gets to it first, please feel free!

**Comment by tonylukasavage** [comment]
+1, eager to use it as well

**Comment by awochna** [comment]
Thanks for the +1, @tonylukasavage .

Would you mind taking a loot at my pull request and giving feedback if you have any?

**Comment by SeyZ** [comment]
@awochna @tonylukasavage I updated the documentation to be more compliant ;)

**Comment by awochna** [comment]
Great, thanks! I like it.
