### ISSUE TITLE
Allow meta option to be a function

### ISSUE THREAD

**Issue by paulwalker** [SeyZ/jsonapi-serializer#67]
I have dynamic meta data per item instance and right now it appears I am only able to accomplish this by creating a new schema every time?

**Comment by allistercsmith** [comment]
Not sure if it's exactly what you're looking for, but I've opened a new issue for allowing dynamic meta to be passed into the serialise method. You can find it here: #72

**Comment by SeyZ** [comment]
Hey @paulwalker @allistercsmith !

I've added the possibility to set a function for the meta option:

```
      var dataSet = {
        id: '1',
        firstName: 'Sandro',
        lastName: 'Munda',
      };

      var json = new JSONAPISerializer('user', {
        attributes: ['firstName', 'lastName'],
        meta: {
          count: function (record) {
            expect(record).to.be.eql({
              id: '1',
              firstName: 'Sandro',
              lastName: 'Munda',
            });

            return 1;
          }
        }
      }).serialize(dataSet);
```

Does that make sense for your issue? Please, reopen this issue if not!
