### ISSUE TITLE
JSON objects in the `attributes`

### ISSUE THREAD

**Issue by pwalczyszyn** [SeyZ/jsonapi-serializer#68]
One of my attributes is a JSON object that I don't wan't to define as a relationship. I also don't know the structure/attributes of this object. How can I define it to embed it as-is in the `attributes` section? As I understand the spec this is actually allowed construct.

So basically what I'm expecting is something like this:

```json
{
  "links": {
    "self": "http://example.com/articles/1"
  },
  "data": [
    {
      "type": "articles",
      "id": "1",
      "attributes": {
        "id": 1,
        "object-attribute": {"unknown-prop": "value"}
      }
    }
  ]
}
```

**Comment by SeyZ** [comment]
Hey @pwalczyszyn Thanks for report! I think I fixed the problem on my previous commit.
Can you check if it's ok for you using the master branch?

**Comment by pwalczyszyn** [comment]
@SeyZ yes the `master` branch works fine for :)
