### ISSUE TITLE
2.1 breaks semver 

### ISSUE THREAD

**Issue by esatterwhite** [SeyZ/jsonapi-serializer#69]
2.1 is a breaking change and should be published to npm as 3.0

please un publish this, and republish the package as `3.0` and `3.0.1` to make this right. 

`npm unpublish`

**Comment by andjosh** [comment]
:heavy_plus_sign:

**Comment by SeyZ** [comment]
You're right, sorry guys

**Comment by SeyZ** [comment]
I will not unpublish the 2.1 version because a lot of people already updated to this version. I won't break things twice (and make the same mistake).

**Comment by SeyZ** [comment]
Bump 3.0.0
