### ISSUE TITLE
Allow attribute null values

### ISSUE THREAD

**Issue by pwalczyszyn** [SeyZ/jsonapi-serializer#70]
Serializer converts `null` value into a `"null"` string. Shouldn't it leave `null` instead?

**Comment by SeyZ** [comment]
Hey @pwalczyszyn Can you share a code example?

In the test, you already have a function that tests the `null` value and it passes.

```
  describe('Null data resource', function () {
    it('should be returned as NULL', function (done) {
      var resource = null;

      var json = new JSONAPISerializer('users', {
        attributes: ['firstName', 'lastName'],
      }).serialize(resource);

      expect(json).to.have.property('data').and.to.equal(null);
      done(null, json);
    });
  });
```

**Comment by pwalczyszyn** [comment]
@SeyZ the test is for the resource values, I'm talking about attribute values. For example I have this object that I wan't to serialize:

```javascript
var article = {
  id: null,
  title: 'Some Title'
};
```
After serialization and deserialization I'm getting value of `id` attribute as string `"null"`.

**Comment by tonylukasavage** [comment]
@pwalczyszyn from the [jsonapi spec](http://jsonapi.org/format/#document-resource-object-identification):

> **Identification**
> 
> Every resource object **MUST** contain an id member and a type member. The values of the id and type > members **MUST** be strings.

jsonapi-serializer is doing you a favor by enforcing the spec. I would consider this issue invalid, unless there's other attributes not listed in the spec that are inadvertently being converted to strings.

**Comment by pwalczyszyn** [comment]
@tonylukasavage you are right, closing this issue.
thx

**Comment by pwalczyszyn** [comment]
Sorry reopening ;) The same spec allows not specifying IDs when creating new resources: http://jsonapi.org/format/#crud-creating And that's my case.

Only requirement is to have `type`.

So when I don't specify an `id` and I serialize my object it always gives me: `id: 'undefined'`

**Comment by SeyZ** [comment]
@pwalczyszyn It's not fixed ;)
