### ISSUE TITLE
Allow dynamic meta content

### ISSUE THREAD

**Issue by allistercsmith** [SeyZ/jsonapi-serializer#72]
@SeyZ - first off, thumbs up for a great framework-agnostic, lightweight and easy-to-use library :+1: Just what I've been looking for!

The only thing I find lacking at the moment is the ability to add dynamic meta data at the point of serialisation. At the moment, you can only add meta when creating the serialiser instance, and seems a bit unintuitive to recreate the serialiser every time I need to change the meta.

In my case, I'm looking to add some extra information regarding pagination, such as total count. In keeping with the spec, this type of additional information should live in the top-level meta. An example of this can be seen in the extensions section here, under _Profiles:_ [link](http://jsonapi.org/extensions/#profiles)

The easiest way I can think of is to add an optional _opts_ param to the serialise method. You can then specify a meta value in _opts_, and on the plus side, this also serves as a nice container if you want to allow any other options for the serialise method in the future. We can then merge it with any existing meta from the serialiser instance like so:

```
module.exports = function (collectionName, records, opts) {
  this.serialize = function (records, opts) {
    var that = this;
    var payload = {};

    ...

    if (that.opts.meta) {
      payload.meta = that.opts.meta;
    }

    if (opts.meta) {
      if (payload.meta) {
        for (var i in opts.meta) {
          payload.meta[i] = opts.meta[i];
        }
      } else {
        payload.meta = opts.meta;
      }
    }

    ...
```

Just gave it a run-through, and seems to work well. If anybody seconds the approach, I'm happy to do a PR.

**Comment by SeyZ** [comment]
Hey @allistercsmith ! Thanks for your message, I appreciate!

Good idea for the dynamic meta. You're totally right, it's not good to recreate a serializer each time the meta change.

I like the idea to pass an `opts` to the serialize method too. You should use the lodash merge method to merge the objects `opts.meta` and `that.opts.meta` :)

PR is of course welcomed!

**Comment by sazzer** [comment]
Once we're passing options in to the serialize function, it could be useful to make them available to all of the various functions that are declared as part of the schemas as well. That way, we can - for example - make the request details available inside the functions that are used to generate URLs, instead of having to solely depend on the record data or else re-creating the schema every time.

**Comment by mrkvon** [comment]
(WIP)
The first (and possibly sufficient) step, as suggested in #67 could be: Allow the meta parameter in Serializer opts to be a function (or object of functions if one wishes to be more strict).

```js
var UserSerializer = new JSONAPISerializer('users', {
  attributes: ['firstName', 'lastName']
});

var users = UserSerializer.serialize(data);

})
```

It would imho be the least complex solution.

**Comment by bradbumbalough** [comment]
This was a requirement for my use case. Ended up switching to https://github.com/kutlerskaggs/json-api-ify as they provide a somewhat dynamic meta option.

**Comment by SeyZ** [comment]
Hey @allistercsmith @bradbumbalough @mrkvon @sazzer 

I've added the possibility to set a function for the meta key:
https://github.com/SeyZ/jsonapi-serializer/blob/master/test/serializer.js#L198

If you need a dynamic meta for a relationship, it was already implemented:
https://github.com/SeyZ/jsonapi-serializer/blob/master/test/serializer.js#L1549

I think it's fixed this issue, right? @bradbumbalough Hope you will come back here 👍  💃
