### ISSUE TITLE
unable to import this library in my ember-app

### ISSUE THREAD

**Issue by rishirajdev** [SeyZ/jsonapi-serializer#88]
Hi,

How can I import jsonapi-serializer libraries in my ember-app.

I did install ember-browserify  and then npm install jsonapi-serializer --save-dev

but not able to use it my ember-app

Is there other way to do it

**Comment by SeyZ** [comment]
Hey @rishirajdev 

I use (and love) Ember a lots too. But I never tested importing a browerify jsonapi-serializer into an Ember app. I'm not sure to understand the purpose of doing this. Ember-data has its own [JSONAPISerializer](http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html).

Maybe you can explain me what's your usecase?

**Comment by rishirajdev** [comment]
hi @SeyZ 

Actually my backend api accepts the json while sending post request in  <a href="https://github.com/rishirajdev/jsonAPIUnmarshal/blob/master/jsonFormat">this format</a>.

I have a user and address model in emberjs with user hasMany address relationship & address belongsTo user. I want ember to send the post request in the above json format instead of <a href="http://jsonapi.org/format/#crud-creating">json api crud creating format</a>

I am storing using the user and address details in the same json document in mongodb.

Below will be document structure in mongodb:

`{
        "_id" : ObjectId("573af5f37c5f5b2068861bd7"),
        "first_name" : "DEF",
        "last_name" : "jkl",
        "username" : "def1234",
        "contact" : "12345",
        "secondary_contact" : "",
        "email" : "abc@capital.com",
        "company_name" : "capital",
        "job_title" : "Associate",
        "years_of_exp" : "",
        "description" : "dhfgvvjdfdk",
        "address" : [ 
            { 
               "city":"abc",
               "country":"def",
               "state":"MH",
               }    
           ]
}`

**Comment by ubuntuvim** [comment]
I also use "jsonapi-serializer" to process the data in my Ember project, and support good. My Ember project is using `JSONAPIAdapter`. You can refer to my usage.
[adapter-serializer-server](https://github.com/ubuntuvim/adapter-serializer-server)

**Comment by ubuntuvim** [comment]
@rishirajdev 
I also use "jsonapi-serializer" to process the data in my Ember project, and support good. My Ember project is using JSONAPIAdapter. You can refer to my usage.
[adapter-serializer-server](https://github.com/ubuntuvim/adapter-serializer-server)

**Comment by SeyZ** [comment]
Hey @rishirajdev I close this issue. @ubuntuvim uses jsonapi-serializer in his Ember app and it seems to work fine. Please, reopen this issue if you still have a problem 👍
