### ISSUE TITLE
Top level ID access for compound document links

### ISSUE THREAD

**Issue by m-bodmer** [SeyZ/jsonapi-serializer#9]
Here is my desired output:

```javascript
    type: "posts",
    id: "236",
    attributes: {
        title: "A post to boost your energy",
    },
    relationships: {
        subcategory: {
            data: {
                type: "subcategories",
                id: "114"
            },
            links: {
                // I want to get the ID of the current "post"... in this case it is 236
                self: "http://localhost:3000/posts/236/relationships/subcategory"
            }
        },
    }
```

In my jsonapi-serializer config, I have the following:

```javascript
    attributes: ['title'],
    subcategory: {
        ref: 'id',
        attributes: ['id'],
        relationshipLinks: {
            self: function(topLevelResourceID) {
                // For the above sample out, I want to be able to get id 236 here
                return apiEndpoint + topLevelResourceID.id + '/relationships/classes';
            }
        }
    }
```

Is this possible?

**Comment by SeyZ** [comment]
@m-bodmer You can now access to the current serialized document in the links function.

Something like:

    attributes: ['title'],
    subcategory: {
        ref: 'id',
        attributes: ['id'],
        relationshipLinks: {
            self: function(foo, bar) {
                // For the above sample out, I want to be able to get id 236 here
                return apiEndpoint + foo.id + '/relationships/classes';
            }
        }
    }

Thoughts?

**Comment by m-bodmer** [comment]
If the `self` function looks like `self: function(foo)`, then `foo` is the top level object? (From the above example it would be `posts`). Similarly, if the function signature looks like `self: function(foo, bar)`, is `foo` still the top level object?

**Comment by SeyZ** [comment]
@m-bodmer 

```
attributes: ['title'],
subcategory: {
    ref: 'id',
    attributes: ['id'],
    relationshipLinks: {
        self: function(record, current) {
            return apiEndpoint + record.id + '/relationships/classes';
        }
    }
}
```

`record` is, in your example, something like:
```
{
    id: 203,
    title: 'Hockey practice',
    slug: 'hockey-practice',
    subcategories: {
        description: 'Practices for strength, balance, flexibility, and vitality.',
        id: 114,
        title: 'Vitality'
    },
}
```

current is, in your example, something like:
```
subcategories: {
  description: 'Practices for strength, balance, flexibility, and vitality.',
  id: 114,
  title: 'Vitality'
}
```

Does it fix your issue?

**Comment by m-bodmer** [comment]
Yep! Thanks!
