### ISSUE TITLE
empty relationships should not be returned as part of the payload

### ISSUE THREAD

**Issue by jamesdixon** [SeyZ/jsonapi-serializer#93]
I just upgraded from 2.x to 3.x and it seems that even if no relationships are present in the options, an empty relationships object is returned as part of the serialized payload:

Options passed to serializer:

```javascript
{ topLevelLinks: { self: 'https://localhost:3001/billing-periods' },
  dataLinks: { self: [Function] },
  attributes:
   [ 'businessId',
     'startsAt',
     'endsAt',
     'status',
     'createdAt',
     'updatedAt',
     'subtotal',
     'credits',
     'payments' ],
  typeForAttribute: [Function],
  keyForAttribute: [Function] }
```

Serialized payload:

```javascript
{
      "type": "billing-period",
      "id": "2",
      "links": {
        "self": "https://localhost:3001/billing-periods/2"
      },
      "attributes": {
        "businessId": 1,
        "startsAt": "2017-03-30T12:25:31.468Z",
        "endsAt": "2017-04-06T12:25:31.468Z",
        "status": "review",
        "createdAt": "2016-06-11T22:32:55.904Z",
        "updatedAt": "2016-06-11T22:32:55.904Z",
        "subtotal": "66899.00",
        "credits": "0",
        "payments": "0"
      },
      "relationships": {}
}
```

Although the spec states that a `relationships` member **MUST** be an object, it also says that a resource object **MAY** contain a `relationships` member, but it's not required (http://jsonapi.org/format/#document-resource-objects). 

The way that I'm interpreting is that `relationships` is an optional member of a resource object, but if it is included, then it must be an object.

I'm going to go ahead submit a PR -- let me know if you agree with my analysis. 

Cheers,
James

**Comment by sarus** [comment]
@SeyZ  would you be willing to push out a new release with this fix?  All my tests are failing now because an empty relationship object is returned.  I've sort of hacked it myself at the moment since I wrapped the serialize method but would be great to have the official fix.

Thanks!

**Comment by sarus** [comment]
Just noticed that v3.5.5 might have reintroduced this issue?  Is anyone else seeing empty relationship objects showing up again?

**Comment by richardcalahan** [comment]
Just installed 3.5.5 and can confirm the empty relationship field. For me it's showing up in the "included" objects.
