### ISSUE TITLE
Does not support circular references between resources

### ISSUE THREAD

**Issue by ghost** [SeyZ/jsonapi-serializer#96]
`"data": [
    {
        "type": "users",
        "id": "9",
        "attributes": {
            "name": "Foo",
            "last-name": "Bar",
        },
        "relationships": {
            "profile": {
                "data": {
                    "type": "profiles",
                    "id": "1"
                }
            }
        }
    }
  ],
  "included": [
    {
        "type": "profiles",
        "id": "1",
        "attributes": {
            "marital-status": "single",
            "job-type": "full-time"
        },
        "relationships": {
            "user": {
                "data": {
                    "type": "users",
                    "id": "9"
                }
            }
        }
    }
  ]`

**Comment by SeyZ** [comment]
Fixed
