### ISSUE TITLE
Allow meta inside data

### ISSUE THREAD

**Issue by shukhero1** [SeyZ/jsonapi-serializer#97]
@SeyZ  Great Serializer but unfortunately does not support metadata per record. 

```
{
  "data": [{
    "type": "users",
    "id": "1",
    "attributes": {
      "first-name": "Sandro",
      "last-name": "Munda"
    },
    meta : {
      nick-name : ''
   }
 }, {
    "type": "users",
    "id": "2",
    "attributes": {
      "first-name": "John",
      "last-name": "Doe"
    },
    meta : {
      nick-name : ''
    }
  }]
}
```

**Comment by maxwerr** [comment]
Curious about the use case for this, [the standard](http://jsonapi.org/format/#document-meta) seems to imply `meta` only makes sense at root-level or subgroup level (related, maybe included?).

**Comment by shukhero1** [comment]
Meta inside data is supported by JSON:API v1.0,  it is  mostly used in collections when data is specific to a record but  can not be represented as  relationship or attribute.

**Comment by SeyZ** [comment]
@maxwerr I think @shukhero1 is right: http://jsonapi.org/format/#document-resource-objects
Does that make sense?

**Comment by SeyZ** [comment]
It's now available:
https://github.com/SeyZ/jsonapi-serializer/blob/master/test/serializer.js#L225
